### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ultra-pool** [Anjmao/candy#4]
"> candy-crust@1.0.0 postinstall D:\phaser-candy-crush-github_master
> bower install && gulp heroku-build

gulp-typescript: noExternalResolve is deprecated - use noResolve instead
  The non-standard option noExternalResolve has been removed as of gulp-typescript 3.0.
  Use noResolve instead.
  More information: http://dev.ivogabe.com/gulp-typescript-3/
gulp-typescript: noExternalResolve is deprecated - use noResolve instead
  The non-standard option noExternalResolve has been removed as of gulp-typescript 3.0.
  Use noResolve instead.
  More information: http://dev.ivogabe.com/gulp-typescript-3/
gulp-typescript: noExternalResolve is deprecated - use noResolve instead
  The non-standard option noExternalResolve has been removed as of gulp-typescript 3.0.
  Use noResolve instead.
  More information: http://dev.ivogabe.com/gulp-typescript-3/
gulp-typescript: noExternalResolve is deprecated - use noResolve instead
  The non-standard option noExternalResolve has been removed as of gulp-typescript 3.0.
  Use noResolve instead.
  More information: http://dev.ivogabe.com/gulp-typescript-3/
assert.js:43
  throw new errors.AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (D:\phaser-candy-crush-github_master\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (D:\phaser-candy-crush-github_master\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (D:\phaser-candy-crush-github_master\gulpfile.js:34:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! candy-crust@1.0.0 postinstall: `bower install && gulp heroku-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the candy-crust@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyRig1\AppData\Roaming\npm-cache\_logs\2019-05-27T00_07_02_075Z-debug.log"

Error on npm install errors on windows and it wont work on Linux. Even though Linux was able to install all the needed files.

**Comment by WTFFARIDZ** [comment]
Any update on this?
